# Generated by Django 3.0.6 on 2020-05-18 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_sessions', '0002_session_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.IntegerField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('date_payable', models.DateField(blank=True, null=True)),
                ('total_value_earned', models.FloatField()),
                ('location', models.URLField(blank=True, null=True)),
                ('sessions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='work_sessions.Session')),
            ],
        ),
    ]
